---
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 
    volumes:
      - ./zookeeper-data:/var/lib/zookeeper/data
    networks:
      - kafka-network
  broker:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 86400000
      KAFKA_LOG4J_ROOT_LOGLEVEL: "INFO"
      KAFKA_LOG4J_LOGGERS: "kafka.server=INFO"
    ports:
      - 9092:9092
    networks:
      - kafka-network
    volumes:
      - ./kafka-data:/var/lib/kafka/data
  generator:
    build:
      context: ./generator
    depends_on:
      - broker
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      TRANSACTIONS_PER_SECOND: 100
      STOP_FLAG: "false"
    networks:
      - kafka-network
  detector:
    build:
      context: ./detector
    depends_on:
      - broker
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      LEGIT_TOPIC: streaming.transactions.legit
      FRAUD_TOPIC: streaming.transactions.fraud
    networks:
      - kafka-network
    volumes:
      - ./detector/logs:/usr/app/logs
networks:
  kafka-network:
    driver: bridge
